### ISSUE TITLE
Feature request: show language and license on RFP/ITPs

### ISSUE THREAD

**Issue by FedericoCeratto** [hartwork/wnpp.debian.net#162]
Hello and thanks for your work.
Would you consider showing programming language and license on RFPs and ITPs?
Being able to filter by it would be even better.
Thanks!

**Comment by hartwork** [comment]
Hi Federico,

programming language and license is not information that the debbugs SOAP interface, where the data is fecthed from, seems to expose readily or at all. There's a list of the fields that debbugs provides at https://github.com/hartwork/wnpp.debian.net/blob/4b5437586e8917135e2fe470cd3580a8ea87289b/wnpp_debian_net/debbugs.py#L17-L49 
I may do quick fixes and features but — unless I'm missing something — this doesn't seem quick. What do you think?

Best, Sebastian

**Comment by hartwork** [comment]
I'll close the ticket as out-of-scope for now.
