### ISSUE TITLE
https://wnpp.debian.net seems broken (search requests return blank)

### ISSUE THREAD

**Issue by GLolol** [hartwork/wnpp.debian.net#2]
On both Chrome 66 and Firefox 69, https://wnpp.debian.net/ does not return any results when I give it a query.

Example: https://wnpp.debian.net/?type%5B%5D=ITA&type%5B%5D=ITP&type%5B%5D=O&type%5B%5D=RFA&type%5B%5D=RFH&type%5B%5D=RFP&project=icon-theme&description=&owner%5B%5D=yes&owner%5B%5D=no&col%5B%5D=dust&col%5B%5D=type&col%5B%5D=description&col%5B%5D=installs&sort=dust%3Basc

**Comment by hartwork** [comment]
Confirming the issue, database corruption involved, partially fixed, investigation not done yet. Please stay tuned.

**Comment by hartwork** [comment]
Related bug: https://bugs.mysql.com/bug.php?id=88336

**Comment by hartwork** [comment]
Another quickfix needed in the code. Site is back up as to what I can see. Please re-open as needed.
