### ISSUE TITLE
Forwarded (ITP or RFP) bugs are not found

### ISSUE THREAD

**Issue by codehelp** [hartwork/wnpp.debian.net#214]
Whilst doing some security tracker work, I checked wnpp.debian.net for freeswitch using both the "Project" and "Description" queries, looking for ITP or RFP. Nothing came up.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=389591 exists but is marked as Forwarded.

Other bugs similarly tagged "forwarded" also do not come up in wnpp.debian.net:
* freeswitch #389591
* visit #395573
* flex-sdk #592007
* xul-ext-pencil
* apostrophe 

16 packages in all.

https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=wnpp;dist=unstable

**Comment by hartwork** [comment]
@codehelp any thoughts?

**Comment by hartwork** [comment]
Closing because of no reply

**Comment by FranklinYu** [comment]
I came across the same issue for `chezmoi` (bug 1012721). The issue is forwarded to a GitHub issue, and the packager is still (actively) working on packaging the software. I feel that wnpp should include bugs like this.

**Comment by FranklinYu** [comment]
I chatted with some DD, who believed that “Forwarded” is closer to “see also”; in this case, it essentially means something like

> You can find more updates and discussion in this GitHub issue, but it is still WIP, and the author still intend to fix it.

In addition, [my RFP request of the same package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012832) was deduplicated onto bug 1012721. Both pieces of evidence make me believe that showing it in the search result is the right thing to do.

**Comment by hartwork** [comment]
@FranklinYu thanks for your input! I believe that pull request #417 fixes the issue and I have deployed these changes and run a fresh import just now, adding 19 forwarded issues to the database total. At https://wnpp.debian.net/?project=visit I can see that forwarded issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=395573 is now listed.

**Comment by FranklinYu** [comment]
I checked all the packages mentioned above, and they can all be found now. Thank you very much for fixing this!

**Comment by hartwork** [comment]
@FranklinYu my pleasure, have a nice day! :pray:
