### ISSUE TITLE
Please provide an API

### ISSUE THREAD

**Issue by sandrotosi** [hartwork/wnpp.debian.net#251]
Hello,
it would be extremely helpful if you could provide an API an automation could connect to and query for WNPP bugs.

Thanks!

**Comment by hartwork** [comment]
@sandrotosi https://wnpp.debian.net/ is not much more than a UI and a persistent cache of the data provided by [DebbugsSoapInterface](https://wiki.debian.org/DebbugsSoapInterface). So there already is an API to access that very data, and it's closer to the source than https://wnpp.debian.net/ .

**Comment by sandrotosi** [comment]
sure, but searching the bts in python is not that straightforwards, even using `debianbts`. f.e. using `debianbts.get_bugs(package='wnpp', status='open')` it returns 6600+ bugs number, which will then be needed to be queries individually to get the title/body.

OTOH, wnpp.debian.net already has all this information available, they would only need to be exposed via an api

**Comment by hartwork** [comment]
Hi @sandrotosi,

I should add that I have no use for this API myself (and know little about your future use so far) and I have other projects, that are more important to the Software libre community and competing for the same unpaid voluntary time bugdet, e.g. [libexpat](https://libexpat.github.io/).

If someone wants to pay for development of an API, continuous maintenance and operation, there may be a way, but unpaid this API would be a plain waste of my time. If there is interest, contacting me off-GitHub through the e-mail address on my profile would work best.  We can either add prefix "[needs sponsoring]" to the title of this ticket or close it. What do you think?

**Comment by hartwork** [comment]
@sandrotosi someone mentioned https://wiki.debian.org/UltimateDebianDatabase/ at #252 . Maybe it has, what you need.
