### ISSUE TITLE
There is no issue

### ISSUE THREAD

**Issue by Maxzor** [hartwork/wnpp.debian.net#252]
Thank you for the tool, looks great!
Is it related to https://wiki.debian.org/UltimateDebianDatabase/ ?

**Comment by hartwork** [comment]
:smile:  Hi @Maxzor , thank you!
The data is fetched from https://wiki.debian.org/DebbugsSoapInterface. Any specific reason you're asking?

**Comment by Maxzor** [comment]
No, I am getting to know the debian ecosystem.
