### ISSUE TITLE
wnpp.debian.net HTTPS certificate expired

### ISSUE THREAD

**Issue by hosiet** [hartwork/wnpp.debian.net#3]
I'm not sure if it is correct to report this problem here, but this site is currently unavailable due to invalid (expired) certificate.

If you have access to the running instance, please help to fix this issue. Thanks!

**Comment by hartwork** [comment]
I'm aware. I hope to have the issue fixed by Monday and also improve the setup so that it won#t happen like that again. Sorry for the inconvenience.

**Comment by hartwork** [comment]
Fixed
