### ISSUE TITLE
Improve truncated package names

### ISSUE THREAD

**Issue by guillemj** [hartwork/wnpp.debian.net#4]
Hi!

The current site truncates long package names with [..], but there's no apparent way (I might have missed it!) to get the non-truncated names, except for clicking on the link and checking the original bug.

It would be nice if it would be possible to select to get no truncation, and when truncating to add the full package name as part of the alt text for example?

**Comment by hartwork** [comment]
Hi! Is there a chance that you could provide a patch?

**Comment by guillemj** [comment]
Hmm, for the alt text perhaps, for the selectable truncation I'm afraid that might take too much time as I don't speak php. But I can happily wait until this gets fixed, it's not very urgent, and I'm not a regular user of the site, I just thought it might be a nice improvement to  the layout. :) Thanks!

**Comment by reedjc** [comment]
I was about to open a bug for the same problem. See:
$MAX_PROJECT_LEN = 20;
$MAX_DESCR_LEN = 60;

The project name is much more valuable than the description.

Please increase the $MAX_PROJECT_LEN.

If you are trying to save real estate, then lower the $MAX_DESCR_LEN (after raising the $MAX_PROJECT_LEN ).

**Comment by reedjc** [comment]
By the way, of the packages in stretch main: The first 20 characters of a package name covers at least 94% of the packages. The index.php5 only shows up to first 16 characters as the shrink() loses four for the [...] replacement.

10 :29593 :58.1886
15 :42088 :82.7575
20 :47809 :94.0067
25 :49847 :98.014
30 :50648 :99.589
35 :50811 :99.9096
40 :50846 :99.9784
41 :50851 :99.9882
42 :50853 :99.9921
43 :50857 :100
44 :50857 :100
45 :50857 :100
50 :50857 :100
55 :50857 :100
60 :50857 :100
65 :50857 :100
100 :50857 :100

My problem was with golang- packages.  For those golang- packages, the first 37 characters handles all of them so MAX_PROJECT_SIZE=41.

**Comment by hartwork** [comment]
I have added 18 more characters now for a start. Change is already live.

**Comment by reedjc** [comment]
Thank you. That is helpful.

**Comment by hartwork** [comment]
This seems fixed, please re-open as needed. Current package name truncation works with the first 37-38 characters.
