### ISSUE TITLE
add info about bug reports

### ISSUE THREAD

**Issue by sandrotosi** [hartwork/wnpp.debian.net#5]
Hello,
it would be helpful if wnpp.debian.net could also show the total count of RC bug reports + the total count of other-severity bug reports (say a pkg with 1 critical, 1 serious, 3 normal, 5 wishlist a table cell of `2 (9)`)

thanks

**Comment by hartwork** [comment]
While this feature would be closer to reach now that the old PHP code is replaced with Python and Django, given my other commitments I don't see this ticket as a realistic priority anytime soon. In case you know someone who might want to sponsor development of this feature, please contact me off-GitHub. Thanks for your understanding.
