### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by silascutler** [hartwork/wnpp.debian.net#56]
Hello @hartwork,  This is a fantastic resource.  Is it possible to include some references on the page to help provide a starting point for folks looking to get involved?

Thanks

**Comment by hartwork** [comment]
Hi @silascutler glad to hear! I'm not a Debian developer, I'm not sure what the best references would be. Maybe ideally there would be _one_ link to a page with further links somewhere on official Debian ground, even a wiki page. What do you think?

**Comment by silascutler** [comment]
Absolutely.  I'll keep looking for just such as landing page and will submit a Pull request.  Thanks.
