### ISSUE TITLE
Support query parameter “reporter”

### ISSUE THREAD

**Issue by FranklinYu** [hartwork/wnpp.debian.net#6]
This is a feature request.

For example I would like to check all requests I reported. It already has a “Reporter” field so this feature seems practical.

As a stretch goal, maybe we can have one more parameter called `age-range` accepting values like `20-100`, or half-bounded interval like `50-` (no less than 50) and `-50` (no greater than 50).

**Comment by hartwork** [comment]
Hi @FranklinYu , the code in here is ten years old and not developed any more; it's in maintenance mode at best. If you can make a pull request that is super easy to review, I might have a moment for review, but that's the best I can offer.

**Comment by hartwork** [comment]
The PHP 5 underpinnings of this project have been replaced by Python and Django by now; as a result, adding a reporter field for a filter would be easier to implement in a sustainable way now. @FranklinYu do you still have interest in this feature *or* should it be closed as no longer needed? Please let me know, thanks!

**Comment by hartwork** [comment]
I'll close the issue as assumed-no-longer-needed for now. I'm happy to re-open as needed.
